adding Find-BBServerRepository and tests
pshdo/BitbucketServerAutomation pull request #8
Opened 2017-08-10 23:01 UTC by scott-pickthorn

- adding Find-BBServerRepository that returns all the repositorys that match a repositoryName or wildcard.

2017-08-10 23:26 UTC, splatteredbits requested changes

2017-08-10 23:26 UTC, splatteredbits commented on BitbucketServerAutomation/BitbucketServerAutomation.psd1
Please undo all the whitespace changes. What caused this?

2017-08-10 23:26 UTC, splatteredbits commented on BitbucketServerAutomation/Functions/Find-BBServerRepository.ps1
> +        $repositoryList += Get-BBServerRepository -Connection $Connection -ProjectKey $_.key| Where-Object { $_.name -like $Name }
Indent this line and the next.

2017-08-10 23:26 UTC, splatteredbits commented on BitbucketServerAutomation/Functions/Find-BBServerRepository.ps1
> +    $repositoryList = @()
Remove `$repositoryList`. Let the pipeline return any repository object that matches the `Where-Object` condition.

2017-08-10 23:26 UTC, splatteredbits commented on Tests/Find-BBServerRepository.Tests.ps1
> +    ThenTheRepositoryShouldBeLike -name 'second'
Change this to something like `ThenRepositoryReturned`. You pass it a list of names of repositories that should be returned. No wildcard matching required/needed.

2017-08-10 23:26 UTC, splatteredbits commented on BitbucketServerAutomation/Functions/Find-BBServerRepository.ps1
> +function Find-BBServerRepository
Missing license notice.

2017-08-10 23:26 UTC, splatteredbits commented on Tests/Find-BBServerRepository.Tests.ps1
> +& (Join-Path -Path $PSScriptRoot -ChildPath 'Initialize-BitbucketServerAutomationTest.ps1' -Resolve)
Missing license notice.

2017-08-11 17:34 UTC, scott-pickthorn commented on BitbucketServerAutomation/Functions/Find-BBServerRepository.ps1
> +function Find-BBServerRepository
Done

2017-08-11 17:35 UTC, scott-pickthorn commented on BitbucketServerAutomation/BitbucketServerAutomation.psd1
Done

2017-08-11 17:35 UTC, scott-pickthorn commented on Tests/Find-BBServerRepository.Tests.ps1
> +& (Join-Path -Path $PSScriptRoot -ChildPath 'Initialize-BitbucketServerAutomationTest.ps1' -Resolve)
Done

2017-08-11 18:16 UTC, splatteredbits approved these changes

2017-08-11 18:16 UTC, merged