Creating get bb server changes function
pshdo/BitbucketServerAutomation pull request #9
Opened 2017-08-16 21:29 UTC by scott-pickthorn

Created `Get-BBServerChanges` function for getting changes between two commits or refs.

2017-08-16 22:29 UTC, splatteredbits requested changes

2017-08-16 22:29 UTC, splatteredbits commented on BitbucketServerAutomation/Functions/Get-BBServerChanges.ps1
> +        $resourcePath = ('projects/{0}/repos/{1}/compare/changes?from={2}&to={3}' -f $ProjectKey, $RepoName, $From, $To)
Make sure to URL encode the `$From` and `$To` parameters, e.g. `[Web.HttpUtility]::UrlEncode($To)`.

2017-08-16 22:29 UTC, splatteredbits commented on BitbucketServerAutomation/Functions/Get-BBServerChanges.ps1
> +            $changesList += $changes.values
Don't add the changes to a list. Just return `$changes.values` to the pipeline, e.g.

    $changes.values

2017-08-16 22:29 UTC, splatteredbits commented on BitbucketServerAutomation/Functions/Get-BBServerChanges.ps1
> +    return $changesList
Remove.

2017-08-16 22:29 UTC, splatteredbits commented on BitbucketServerAutomation/Functions/Get-BBServerChanges.ps1
> +    $changesList = @()
Remove (see comment below).

2017-08-16 22:29 UTC, splatteredbits commented on BitbucketServerAutomation/BitbucketServerAutomation.psd1
> +* Created `Get-BBServerChanges` function for getting changes between two commits or refs.
Remove the ` or refs` clause.

2017-08-17 16:51 UTC, scott-pickthorn commented on BitbucketServerAutomation/BitbucketServerAutomation.psd1
> +* Created `Get-BBServerChanges` function for getting changes between two commits or refs.
Done

2017-08-17 16:51 UTC, scott-pickthorn commented on BitbucketServerAutomation/Functions/Get-BBServerChanges.ps1
> +    return $changesList
Done

2017-08-17 16:52 UTC, scott-pickthorn commented on BitbucketServerAutomation/Functions/Get-BBServerChanges.ps1
> +            $changesList += $changes.values
Done

2017-08-17 16:52 UTC, scott-pickthorn commented on BitbucketServerAutomation/Functions/Get-BBServerChanges.ps1
> +        $resourcePath = ('projects/{0}/repos/{1}/compare/changes?from={2}&to={3}' -f $ProjectKey, $RepoName, $From, $To)
Done

2017-08-17 16:52 UTC, scott-pickthorn commented on BitbucketServerAutomation/Functions/Get-BBServerChanges.ps1
> +    $changesList = @()
Done

2017-08-17 16:53 UTC, splatteredbits requested changes

2017-08-17 16:53 UTC, splatteredbits commented on BitbucketServerAutomation/Functions/Get-BBServerChanges.ps1
> +        $resourcePath = ('projects/{0}/repos/{1}/compare/changes?from={2}&to={3}' -f $ProjectKey, $RepoName, [Web.HttpUtility]::UrlEncode($From), [Web.HttpUtility]::UrlEncode($To))
Will you add a test for this? Create from and to branches that have a character that needs to be encoded, e.g. `feature/one`, `release/major`, etc.

2017-08-17 17:06 UTC, scott-pickthorn commented on BitbucketServerAutomation/Functions/Get-BBServerChanges.ps1
> +        $resourcePath = ('projects/{0}/repos/{1}/compare/changes?from={2}&to={3}' -f $ProjectKey, $RepoName, [Web.HttpUtility]::UrlEncode($From), [Web.HttpUtility]::UrlEncode($To))
Done

2017-08-17 18:08 UTC, splatteredbits approved these changes

2017-08-17 18:08 UTC, merged